- {path: /customer-list, controller: \Mpwarapp\Home\Controller\Customer, action: show_all}
- {path: /customer-vip-list, controller: \Mpwarapp\Home\Controller\Customer, action: show_vip_all}
- {path: /customer-show, controller: \Mpwarapp\Home\Controller\Customer, action: show}

