- {path: /customer-list-json, controller: \Mpwarapp\Home\Controller\Customer, action: showCustomerListJSON}
- {path: /customer-list-smarty, controller: \Mpwarapp\Home\Controller\Customer, action: showCustomerListSmarty}
- {path: /customer-list-twig, controller: \Mpwarapp\Home\Controller\Customer, action: showCustomerListTwig}
- {path: /customer-show, controller: \Mpwarapp\Home\Controller\Customer, action: show}

