router:
    class: Mpwarfw\Component\Routing\Router
    arguments:
      - "@yml_parser"
      - "/var/www/framework16/Mpwarapp/app/routes.yml"
    public: true

yml_parser:
    class: Symfony\Component\Yaml\Parser
    public: true

SmartyTemplate:
    class: Mpwarfw\Component\Template\SmartyTemplate
    arguments:
      - "@Smarty"
      - "/var/www/framework16/Mpwarapp/src/home/view"
    public: true

Smarty:
    class: Smarty
    public: false

TwigTemplate:
    class: Mpwarfw\Component\Template\TwigTemplate
    arguments:
      - "@TwigEnvironment"
    public: true

TwigEnvironment:
    class: Twig_Environment
    arguments:
      - "@TwigLoader"
      - "['cache' => '/var/www/html/framework16/Mpwarapp/src/home/cache', 'debug' => 'false']"
    public: false
    tags:
      - example
      - twig

TwigLoader:
    class: Twig_Loader_Filesystem
    arguments:
      - "/var/www/framework16/Mpwarapp/src/Home/View"
    public: false

PDOConnection:
    class: Mpwarfw\Component\Database\PDOConnection
    arguments:
      - "localhost"
      - "mpwar_frameworks"
      - "root"
      - "vagrantpass"
    public: true

ResponseHTTP:
    class: Mpwarfw\Component\Response\ResponseHTTP
    public:   true

ResponseJSON:
    class: Mpwarfw\Component\Response\ResponseJSON
    public: true

Translator:
  class: Mpwarfw\Component\i18n\Translator
  arguments:
      - "@yml_parser"
  public: true
